### PR TITLE
[FEAT] support to serialize Findings as JSON

### PR DESCRIPTION
**Pull request by mhnrv**
Added a couple of functions to serialize the Findings class objects as JSON representations.

### CODE REVIEW

**Comment by izar** [comment]
hi and thanks for the PR! How is this different from the current json output capability (./tm.py [...] --json JSON_FILE) ?

**Comment by mhnrv** [comment]
I just tweaked the script to only show the threats by calling 

```python
from pytm.pytm import TM

tm = TM()
tm.resolve() # instead of tm.process()
for finding in tm.findings:
  print(finding.to_json())
```

This way, one can view the findings and the corresponding target instead of the entire model. That is just my opinion 😅

**Comment by izar** [comment]
I'm a bit confused perhaps about the use case you have in mind. 
How would this be different from jq '.findings' on the file generated by --json ?

**Comment by izar** [comment]
Hi, @mohan-ravichandran , can this be closed ?

**Comment by izar** [comment]
No answer from author.

**Pull request closed without merging**
