### PR TITLE
formatted with black

### PR DESCRIPTION
**Pull request by nineinchnick**
Formatted all code with Black and fixed all flake8 issues.
Added Black and flake8 to CONTRIBUTING.md

### CODE REVIEW

**Review by izar — COMMENTED** [review]
Let me check this out a bit more before committing.

**Comment by izar** [comment]
Let's add some more code, there are a couple of big things in the pipeline, then format before hitting the next pip release.

**Comment by nineinchnick** [comment]
Can you reconsider merging this earlier? I'll resolve any conflicts in my PRs if needed. I just forgot to disable autoformating in my editor and have to rebase everything manually.

**Comment by izar** [comment]
I'd really prefer to wait a bit longer.

Thanks,

--izar

**Pull request closed without merging**
