### PR TITLE
rework nested boundaries

### PR DESCRIPTION
**Pull request by redshiftzero**
In #54 @jdcallet reports an issue with nested boundaries: _all_ boundaries are being nested in the order they're defined. This PR builds on their fix taking the approach described [here](https://github.com/izar/pytm/pull/54#discussion_r343463675).

I've tested this on a [more complicated threat model](https://gist.github.com/redshiftzero/ef408324138d1a53d29d76fc15723f37) example and the boundaries are rendering as expected in the nested/non-nested case (the PNGs are huge so not attaching here, but one can test for themselves via `./sd.py --debug --dfd | dot -Tpng -o dfd` both on `master` and on this branch).

### CODE REVIEW

**Review by izar — APPROVED** [review]

**Comment by redshiftzero** [comment]
want me to rebase out the commit from @jdcallet I cherry picked in here? (to resolve the conflicts)

**Comment by izar** [comment]
Yup, looks good from my side, could you please test and confirm?

**Comment by redshiftzero** [comment]
yep, just tested latest `master`, all looks good

**Comment by izar** [comment]
Great, pushing to Pypi, thanks a lot to you and @jdcallet !

**Pull request merged**
